# Generated by Django 5.1.4 on 2025-01-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choboionline', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='choboionline_name_6b5128_idx',
            old_name='choboionline_name_6b5128_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='choboionline_id_cbceb7_idx',
            old_name='choboionline_id_cbceb7_idx',
        ),
    ]
