# Generated by Django 5.1.4 on 2025-01-27 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choboionline', '0003_rename_choboionline_name_6b5128_idx_choboionlin_name_6b5128_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='choboionlin_name_6b5128_idx',
            old_name='choboionline_name_6b5128_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='choboionlin_id_cbceb7_idx',
            old_name='choboionline_id_cbceb7_idx',
        ),
    ]
