# Generated by Django 5.1.4 on 2025-01-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choboionline', '0005_categorytranslation_producttranslation_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='choboionline_name_6b5128_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='choboionline_id_cbceb7_idx',
        ),
    ]
